name: One and Done CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include:
          - elixir: "1.18"
            erlang: "27.2"

          # Oldest-supported Erlang and Elixir versions.
          - elixir: "1.14.5-otp-25"
            erlang: "25.3.2"
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1.18
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.erlang }}

      - name: Retrieve Mix cache
        uses: actions/cache@v4
        id: "mix-cache"
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.erlang }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.erlang }}-

      - name: Install Mix dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run credo
        run: mix credo --strict

      # Compile for the test env before test to catch any compiler errors + warnings
      - name: Precompile
        run: mix compile --warnings-as-errors

      # Run tests with compiler warnings causing a failure
      - name: Run tests
        run: mix test --warnings-as-errors
