name: "Publlish to Hex"

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Set up Elixir and Erlang
        uses: erlef/setup-beam@v1.18
        with:
          elixir-version: "1.18"
          otp-version: "27.2"

      - name: Install Mix dependencies
        run: mix deps.get

      # https://hex.pm/docs/publish#publishing-from-ci
      - name: Publish to Hex
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
